sudo: false
language: node_js
node_js:
  - "10.15.1"
branches:
  only:
    - develop
install:
  - npm install
  - npm install -g coverage
cache:
  directories:
    - "node_modules"
script:
  - npm run test
after_success:
  - npm run coverage


